language: node_js
node_js: 
  - "8"

# cache this directory
cache:
  directories:
    - node_modules

# S: Build Lifecycle
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli

install:
  - npm install
  
before_script:
  - npm install -g gulp

script:
  - git submodule init #用于更新主题,更新源为自己的主题项目，否则会clone最新NexT主题，而官方主题配置文件没有设置
  - git submodule update
  - hexo clean && hexo g
  - gulp default #使用 gulp 对流程进行优化

after_script:
  - cd ./public
  - git init
  - git config user.name "kagomemiao"
  - git config user.email "yusie@live.cn"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

# E: Build LifeCycle

branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/kagomemiao/kagomemiao.github.io.git
   #设置GH_REF，注意更改yourname
